apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thock-redpanda-ingress
  namespace: thock-prod
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.middlewares: "thock-prod-swagger-admin-ip-whitelist@kubernetescrd"
spec:
  tls:
    - hosts:
        - api.thock.site
      secretName: thock-tls
  rules:
    - host: api.thock.site
      http:
        paths:
          - path: /redpanda
            pathType: Prefix
            backend:
              service:
                name: redpanda-console
                port:
                  number: 8090

