apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thock-swagger-ingress
  namespace: thock-prod
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.middlewares: "thock-prod-swagger-admin-ip-whitelist@kubernetescrd"
spec:
  tls:
    - hosts:
        - api.thock.site
      secretName: thock-tls
  rules:
    - host: api.thock.site
      http:
        paths:
          - path: /swagger-ui.html
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
          - path: /v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
          - path: /member-service/v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
          - path: /product-service/v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
          - path: /market-service/v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
          - path: /payment-service/v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
          - path: /settlement-service/v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080

