spring:
  datasource:
    url: jdbc:h2:mem:member-test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  flyway:
    enabled: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

  batch:
    job:
      enabled: false

custom:
  global:
    internalBackUrl: http://localhost:8080
    marketServiceUrl: http://localhost:8083
    paymentServiceUrl: http://localhost:8084

jwt:
  secret: thock-test-jwt-secret-key-which-is-long-enough-32chars
  issuer: "thock-test"
