{
 "title": "주문-결제-재고 흐름 운영 관제",
 "tags": [
  "overview",
  "operations",
  "order",
  "payment",
  "product",
  "loki"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "주문 생성 실패",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "suffix:건" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"market\",log_type=~\"service-error|app\",level=~\"WARN|ERROR\",logger=~\"com[.]thock[.]back[.]market[.]in[.]ApiV1OrderController\"} |= \"주문 생성 실패\"[$__range]))"
    }
   ]
  },
  {
   "title": "환불 처리 실패",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "suffix:건" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (orderId) (count_over_time({service=\"payment\",log_type=~\"service-error|app\",level=~\"WARN|ERROR\",logger=~\"com[.]thock[.]back[.]payment[.]app[.]PaymentConfirmAndRefundUseCase\"} |= \"환불 실패\" | regexp \"orderId=(?P<orderId>[^, ]+)\"[$__range])))"
    }
   ]
  },
  {
   "title": "재고 예약 실패",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "suffix:건" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (orderNumber) (count_over_time({service=\"product\",log_type=~\"service-error|app\",level=~\"WARN|ERROR\",logger=~\"com[.]thock[.]back[.]product[.]in[.]ProductKafkaListener\"} |= \"Stock event failed.\" |~ \"eventType=RESERVE\" | regexp \"orderNumber=(?P<orderNumber>[^, ]+)\"[$__range])))"
    }
   ]
  },
  {
   "title": "재고 복구 실패",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "suffix:건" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (orderNumber) (count_over_time({service=\"product\",log_type=~\"service-error|app\",level=~\"WARN|ERROR\",logger=~\"com[.]thock[.]back[.]product[.]in[.]ProductKafkaListener\"} |= \"Stock event failed.\" |~ \"eventType=RELEASE\" | regexp \"orderNumber=(?P<orderNumber>[^, ]+)\"[$__range])))"
    }
   ]
  },
  {
   "title": "주문 생성 완료",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:건" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"market\",log_type=~\"service-info|app\",level=\"INFO\"} |= \"주문 생성 완료\"[$__range]))"
    }
   ]
  },
  {
   "title": "환불 처리 완료",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:건" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"market\",log_type=~\"service-info|app\",level=\"INFO\"} |~ \"(전체 환불 완료|부분 환불 완료)\"[$__range]))"
    }
   ]
  },
  {
   "title": "최종 결제 완료",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:건" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (orderId) (count_over_time({service=\"payment\",log_type=~\"service-info|app\",level=\"INFO\",logger=~\"com[.]thock[.]back[.]payment[.]app[.]PaymentCompletedOrderPaymentUseCase|com[.]thock[.]back[.]payment[.]app[.]PaymentConfirmAndRefundUseCase\"} |= \"결제 처리 완료\" | regexp \"orderId=(?P<orderId>[^, ]+)\"[$__range])))"
    }
   ]
  },
  {
   "title": "최종 결제 실패",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:건" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (orderId) (count_over_time({service=\"payment\",log_type=~\"service-error|app\",level=~\"ERROR|WARN\",logger=~\"com[.]thock[.]back[.]payment[.]app[.]PaymentCompletedOrderPaymentUseCase|com[.]thock[.]back[.]payment[.]app[.]PaymentConfirmAndRefundUseCase\"} |= \"결제 처리 실패\" | regexp \"orderId=(?P<orderId>[^, ]+)\"[$__range])))"
    }
   ]
  },
  {
   "title": "재고 예약 완료",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:건" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"product\",log_type=~\"service-info|app\",level=\"INFO\"} |= \"Stock event processed.\" |~ \"eventType=RESERVE\"[$__range]))"
    }
   ]
  },
  {
   "title": "재고 복구 완료",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:건" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"product\",log_type=~\"service-info|app\",level=\"INFO\"} |= \"Stock event processed.\" |~ \"eventType=RELEASE\"[$__range]))"
    }
   ]
  },
  {
   "title": "주요 주문 흐름 최근 5분간 이벤트 발생 건수 추이",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"market\",log_type=~\"service-info|app\",level=\"INFO\"} |= \"주문 생성 완료\"[5m]))",
     "legendFormat": "주문 생성"
    },
    {
     "expr": "sum(count_over_time({service=\"market\",log_type=~\"service-info|app\",level=\"INFO\"} |~ \"(전체 환불 완료|부분 환불 완료)\"[5m]))",
     "legendFormat": "환불 완료"
    },
    {
     "expr": "count(sum by (orderId) (count_over_time({service=\"payment\",log_type=~\"service-info|app\",level=\"INFO\",logger=~\"com[.]thock[.]back[.]payment[.]app[.]PaymentCompletedOrderPaymentUseCase|com[.]thock[.]back[.]payment[.]app[.]PaymentConfirmAndRefundUseCase\"} |= \"결제 처리 완료\" | regexp \"orderId=(?P<orderId>[^, ]+)\"[5m])))",
     "legendFormat": "최종 결제 완료"
    },
    {
     "expr": "count(sum by (orderId) (count_over_time({service=\"payment\",log_type=~\"service-error|app\",level=~\"ERROR|WARN\",logger=~\"com[.]thock[.]back[.]payment[.]app[.]PaymentCompletedOrderPaymentUseCase|com[.]thock[.]back[.]payment[.]app[.]PaymentConfirmAndRefundUseCase\"} |= \"결제 처리 실패\" | regexp \"orderId=(?P<orderId>[^, ]+)\"[5m])))",
     "legendFormat": "최종 결제 실패"
    },
    {
     "expr": "sum(count_over_time({service=\"product\",log_type=~\"service-info|app\",level=\"INFO\"} |= \"Stock event processed.\" |~ \"eventType=RESERVE\"[5m]))",
     "legendFormat": "재고 예약"
    },
    {
     "expr": "sum(count_over_time({service=\"product\",log_type=~\"service-info|app\",level=\"INFO\"} |= \"Stock event processed.\" |~ \"eventType=RELEASE\"[5m]))",
     "legendFormat": "재고 복구"
    }
   ]
  },
  {
   "title": "최종 결제 실패 주요 원인",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, sum by (reason) (count_over_time({service=\"payment\",log_type=~\"service-error|app\",level=~\"ERROR|WARN\",logger=~\"com[.]thock[.]back[.]payment[.]app[.]PaymentCompletedOrderPaymentUseCase|com[.]thock[.]back[.]payment[.]app[.]PaymentConfirmAndRefundUseCase\"} |= \"결제 처리 실패\" | json | line_format \"{{.message}}\" | regexp \"reason=(?P<reason>.*)$\"[$__range])))",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}